baseurl = "baseurl = "https://theresawcheng.netlify.com"
languageCode = "en-us"
#title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
author = "Joel Adams"
title = "Joel Adams"
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
    #description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
    description = "Professional website"
    copyright = "Copyright Â© 2015 Joel Adams"
    copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
    logofile = "img/joel.jpg"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

